services:
  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter_lab
    ports:
      - "${LOCALHOST_JUPYTER_PORT}:${JUPYTER_PORT}"          # Accès depuis le navigateur
    volumes:
      - ./notebooks:/home/jovyan/work   # Synchronisation avec le dossier local
      - ./weather_flow:/home/jovyan/src 
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - big-data-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
    networks:
      - big-data-network    
  
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "${LOCALHOST_KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "${KAFKA_ZOOKEEPER_CONNECT}"
      KAFKA_LISTENERS: "${KAFKA_LISTENERS}"
      KAFKA_ADVERTISED_LISTENERS: "${KAFKA_ADVERTISED_LISTENERS}"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}"
    networks:
      - big-data-network

  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    hostname: spark-master
    user: root
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master", "--host", "spark-master"]
    ports:
      - "${LOCALHOST_SPARK_MASTER_PORT}:${SPARK_MASTER_PORT}"   # Spark master
      - "${LOCALHOST_SPARK_UI_PORT}:${SPARK_UI_PORT}"   # UI
    networks:
      - big-data-network
    volumes:
      - ./spark-scripts:/opt/spark/work-dir
      - ./ivy-cache:/tmp/.ivy2

  spark-worker:
    image: apache/spark:latest
    container_name: spark-worker
    hostname: spark-worker
    depends_on:
      - spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    ports:
      - "${LOCALHOST_SPARK_WORKER_UI_PORT}:${SPARK_WORKER_UI_PORT}"   # UI
    networks:
      - big-data-network

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"   # UI NameNode
      - "9000:9000"   # RPC HDFS
      - "50070:50070" # WebHDFS (important pour InsecureClient)
    volumes:
      - ./hadoop/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=bigdata-cluster
      - HDFS_CONF_dfs_replication=1
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    networks:
      - big-data-network

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    depends_on:
      - namenode
    volumes:
      - ./hadoop/datanode:/hadoop/dfs/data
    environment:
      - CLUSTER_NAME=bigdata-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
    networks:
      - big-data-network
  
  airflow:
    image: apache/airflow:2.7.2
    container_name: airflow
    restart: unless-stopped
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _PIP_ADDITIONAL_REQUIREMENTS=kafka-python hdfs
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__WEBSERVER__WEB_SERVER_HOST=0.0.0.0
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8082
      - AIRFLOW_UID=50000
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8082:8082"  # Web UI Airflow
    command: airflow standalone
    depends_on:
      - kafka
      - namenode
    networks:
      - big-data-network

networks:
  big-data-network:
    driver: bridge
    
    